const jwt = require('jsonwebtoken');
const User = require('../models/user');

const userAuth = async (req,res,next) => {
    try {
        // read the cookies from the request
        const { token } = req.cookies;
        if(!token) {
            throw new Error('Token not found');
        }
        // validate my token and verify the token that is generated by server
        const decodedMessage = jwt.verify(token, 'Nooruddin@786_Dev_Tinder');
        const { _id } = decodedMessage;

        const user = await User.findById(_id);
        if(!user) {
            throw new Error('User not found');
        }

        req.user = user;
        next();
    }
    catch(err) {
        res.status(400).send('ERROR: ' + err.message);
    }
}

module.exports = { 
    userAuth,
 };